#' Creates a Lineline
#'
#' Creates ggplot lineplot through scatterplot points from two numerical
#' columns of a provided dataset. Plot includes x and y axis labels and an
#' optional title. Font size is adjustable. X axis values should not repeat
#' and should be monotomic and unique valued.
#'
#' @param df A data frame or tibble
#' @param x The montomic numerical column series within df to be on the x-axis
#' @param y The numerical column within df to be on the y-axis
#' @param x_lab A string for x-axis label if required. Default is "" (no axis label).
#' @param y_lab A string for y-axis label if required. Default is "" (no axis label).
#' @param title A boolean response if title should be included. Title is a concatenation of axis labels. Default is FALSE
#' @param font_size Size of the font used in the lineplot. Default is 12.
#'
#' @return A ggplot lineplot with points.
#'  The lineplot should have points corresponding to the coordinates of the continuous numerical columns inputted into the funtion.
#'  A line should pass through the points.
#'  The x and y axis labels with show if a label is specified.
#'  The title should be a concatenation of axis labels if set as TRUE.
#'
#' @export
#'
#' @examples
#' data = data.frame("time" = c(0.2, 0.4, 0.8, 1.6, 3.2),
#' "height" = c(0, 15, 30, 45, 60))
#' create_lineplot(df = data, x = time, y = height,
#'                  x_lab = "time", y_lab = "height",
#'                  title = TRUE, font_size = 13)
#'
create_lineplot <- function(df,
                             x,
                             y,
                             x_lab = "",
                             y_lab = "",
                             title = FALSE,
                             font_size = 12) {

  lineplot <- df |>
    ggplot2::ggplot(ggplot2::aes(x = {{x}}, y = {{y}})) +
    ggplot2::geom_point() +
    ggplot2::geom_line() +
    ggplot2::labs(x = x_lab, y = y_lab) +
    ggplot2::theme(text = ggplot2::element_text(size = 12))

  if(title == TRUE && ((x_lab == "") || (y_lab == ""))) {
    stop("Specify both labels to get an autogenerated title")
  }

  if(title == FALSE && ((x_lab == "") && (y_lab == ""))) {
    lineplot <- lineplot + ggplot2::theme(axis.title.y = ggplot2::element_blank(),
                                          axis.title.x = ggplot2::element_blank())
  }

  if(title == TRUE) {
    lineplot <- lineplot + ggplot2::ggtitle(paste(x_lab, y_lab, sep=" vs. "))
  }

  return(lineplot)
}
